name: dl-segmentation
channels:
  - mhworth
dependencies:
   - python=2.7
   - six
   - scipy
   - numpy
   - pandas
   - ipython
   - jupyter
   - ipdb
   - pillow
   - pip:
      - https://storage.googleapis.com/tensorflow/mac/tensorflow-0.8.0-py2-none-any.whl
      - nibabel
      - pydicom
      - medpy
